apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: oc6e1ye99-python
  janus-idp.io/tekton: oc6e1ye99-python
  backstage.io/kubernetes-id: oc6e1ye99-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: oc6e1ye99-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
