apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: oc6e1ye99-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: oc6e1ye99-python 
  name: oc6e1ye99-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: oc6e1ye99-python 
